services:
  server:
    container_name: tts-grpc-server
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - ./server:/app
      - ./common:/app/common
    working_dir: /app
    command: ["python", "server.py"]

  client:
    container_name: tts-rest-client
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - ./common:/app/common
    working_dir: /app
    command: ["uvicorn", "rest_gateway:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    container_name: tts-streamlit-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - client
    volumes:
      - ./frontend:/app

