# config.toml

[server]
headless = true
port = 8501
enableCORS = false

[theme]
base="light"
#primaryColor="#f7b731"
#backgroundColor="#fff8e1"
#secondaryBackgroundColor="#ffeaa7"
#textColor="#2d3436"
#font="sans serif"