# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x03tts\">\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05voice\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\x03 \x01(\t\"\x93\x01\n\nAudioReply\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12\x0e\n\x06\x63hunks\x18\x03 \x03(\t\x12\x12\n\ntime_taken\x18\x04 \x01(\x02\x12\x13\n\x0b\x63hunk_index\x18\x05 \x01(\x05\x12\x14\n\x0ctotal_chunks\x18\x06 \x01(\x05\x12\x12\n\nmessage_id\x18\x07 \x01(\t2\xaa\x01\n\nTTSService\x12/\n\x08Generate\x12\x10.tts.TextRequest\x1a\x0f.tts.AudioReply\"\x00\x12\x37\n\x0eStreamGenerate\x12\x10.tts.TextRequest\x1a\x0f.tts.AudioReply\"\x00\x30\x01\x12\x32\n\x07\x43hatTTS\x12\x10.tts.TextRequest\x1a\x0f.tts.AudioReply\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=22
  _globals['_TEXTREQUEST']._serialized_end=84
  _globals['_AUDIOREPLY']._serialized_start=87
  _globals['_AUDIOREPLY']._serialized_end=234
  _globals['_TTSSERVICE']._serialized_start=237
  _globals['_TTSSERVICE']._serialized_end=407
# @@protoc_insertion_point(module_scope)
