# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common.service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TTSServiceStub(object):
    """TTS service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_unary(
                '/tts.TTSService/Generate',
                request_serializer=service__pb2.TextRequest.SerializeToString,
                response_deserializer=service__pb2.AudioReply.FromString,
                _registered_method=True)
        self.StreamGenerate = channel.unary_stream(
                '/tts.TTSService/StreamGenerate',
                request_serializer=service__pb2.TextRequest.SerializeToString,
                response_deserializer=service__pb2.AudioReply.FromString,
                _registered_method=True)
        self.ChatTTS = channel.stream_stream(
                '/tts.TTSService/ChatTTS',
                request_serializer=service__pb2.TextRequest.SerializeToString,
                response_deserializer=service__pb2.AudioReply.FromString,
                _registered_method=True)


class TTSServiceServicer(object):
    """TTS service definition
    """

    def Generate(self, request, context):
        """Basic TTS inference (unary)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamGenerate(self, request, context):
        """Server streaming response (streaming audio back in chunks)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatTTS(self, request_iterator, context):
        """Bidirectional streaming (for advanced interactive use cases)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TTSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=service__pb2.TextRequest.FromString,
                    response_serializer=service__pb2.AudioReply.SerializeToString,
            ),
            'StreamGenerate': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamGenerate,
                    request_deserializer=service__pb2.TextRequest.FromString,
                    response_serializer=service__pb2.AudioReply.SerializeToString,
            ),
            'ChatTTS': grpc.stream_stream_rpc_method_handler(
                    servicer.ChatTTS,
                    request_deserializer=service__pb2.TextRequest.FromString,
                    response_serializer=service__pb2.AudioReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tts.TTSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tts.TTSService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TTSService(object):
    """TTS service definition
    """

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tts.TTSService/Generate',
            service__pb2.TextRequest.SerializeToString,
            service__pb2.AudioReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamGenerate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tts.TTSService/StreamGenerate',
            service__pb2.TextRequest.SerializeToString,
            service__pb2.AudioReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatTTS(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/tts.TTSService/ChatTTS',
            service__pb2.TextRequest.SerializeToString,
            service__pb2.AudioReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
